### ISSUE TITLE
shuffle BN seems wrong to me

### ISSUE THREAD

**Issue by JaejinCho** [dddzg/MoCo#5]
Hello, thanks for sharing your code.

I wanted to find a code to run MoCo on one GPU so looked at your code especially for shuffle BN. 

Specifically, I looked at four links from here https://github.com/dddzg/MoCo/blob/94125b06235032cf74768709bac36e3ffbeb3f7c/main.py#L87 but it seems not correct. It seems not to do anything different compared to not doing it, i.e., in batch normalization, the batch statistics used for a query and positive key are from still the same mini-batch.

It is possible that I miss other parts so please let me know if I am wrong.

Thanks,
Jaejin Cho

**Comment by dddzg** [comment]
Hi, Jaejin Cho. In [this line](https://github.com/dddzg/MoCo/blob/94125b06235032cf74768709bac36e3ffbeb3f7c/main.py#L49), I simulate multiple GPUs when there is only a GPU. So, there is multiple batch statistics.

By the way, this code is maintained before MoCo's official implementation. I recommend the official version. Global BN seems also work well (In recent papers, they use global BN instead of shuffle BN). So, I guess one GPU could also work. What's more, if your image is large, maybe try to apply for more GPUs, MoCo needs a lot of training iterations.

**Comment by dddzg** [comment]
I think I have already answered this question. Feeling free to re-open this issue if you have any new questions.

**Comment by JaejinCho** [comment]
I see. Thanks for the answer with the pointer! I would check it again sometime.
